---

- name: Update apt repository
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name:
      - gcc
      - make
      - libdbi-perl
      - libdbd-mysql-perl
      - libio-socket-ssl-perl
      - libconfig-tiny-perl
      - liblog-dispatch-perl
      - libmodule-install-perl      
      - libparallel-forkmanager-perl
      - cpanminus
    state: present

- name: Copy mha4mysql-node package to the server
  copy:
    src: ./mha4mysql-node-0.58.tar.gz
    dest: /tmp/mha4mysql-node-0.58.tar.gz
    mode: '0644'

- name: Extract mha4mysql-node archive if directory does not exist
  shell: tar xvf mha4mysql-node-0.58.tar.gz
  args:
    chdir: /tmp

#오프라인으로 필요한 perl 모듈 설치 시작

- name: Create directory on each host
  file:
    path: /usr/local/share/perl/5.30.0/Module/
    state: directory
    mode: '0755'

- name: Copy Install.pod to the remote directory
  copy:
    src: ./Install.pod
    dest: /usr/local/share/perl/5.30.0/Module/
    owner: root
    group: root
    mode: '0644'

#오프라인으로 필요한 perl 모듈 설치 종료



# 아웃바운드 막혀있으면 불가
#- name: Configure CPAN non-interactively
#  shell:
#    cmd: |
#      (echo yes; echo o conf commit) | cpan
#
#- name: Install Module::Install using cpan
#  copy:
#    src: ./Install.pod
#    dest: /usr/local/share/perl/5.30.0/Module/Install.pod
#    mode: '0644'


- name: Build and install mha4mysql-node
  shell: |
    perl Makefile.PL
    make
    make install
  args:
    chdir: /tmp/mha4mysql-node-0.58